services:
  - type: web
    name: servicios-abonados
    env: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python init_db.py
      gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servicios-abonados-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  - name: servicios-abonados-db
    plan: free
    databaseName: servicios_abonados
    ipAllowList: []  # Dejar vacío para acceso público
