"""Enhanced Registro model - 2025-02-09 10:35:18.777801

Revision ID: f591504f7049
Revises: 0716936ba257
Create Date: 2025-02-09 10:35:18.816966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f591504f7049'
down_revision = '0716936ba257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_pago', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        
        # Add explicit index names
        batch_op.create_index(batch_op.f('ix_registro_nombre_compania'), ['nombre_compania'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_numero_despacho'), ['numero_despacho'], unique=True)
        
        # Add explicit foreign key name
        batch_op.create_foreign_key('fk_registro_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        # Drop foreign key with explicit name
        batch_op.drop_constraint('fk_registro_user', type_='foreignkey')
        
        batch_op.drop_index(batch_op.f('ix_registro_numero_despacho'))
        batch_op.drop_index(batch_op.f('ix_registro_nombre_compania'))
        
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('user_id')
        batch_op.drop_column('notas')
        batch_op.drop_column('fecha_pago')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
